name: mlops-example-tensorflow-regression
on: [push]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

  train:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    needs: install-dependencies  # Depends on the completion of install-dependencies job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Train model
        run: python model.py

      - name: Save results
        run: |
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md

          echo "\n## Model Performance" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md

      - name: Show results
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml-publish model_results.png --md >> report.md
          cml-send-comment report.md
