name: mlops-exaple-tensorflow-regression
on: [push]

jobs:
  train:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Install dependencies'
        run: |
          pip install -r requirements.txt

      - name: 'Train model'
        run: python model.py

      - name: 'Save results'
        run: |

          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md

          echo "\n## Model Performance" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md

      - name: 'Show results'
        run: |
          cml-publish model_results.png --md >> report.md
          cml-send-comment report.md
